apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: syslog-ng
  name: syslog-ng
spec:
  ports:
    - name: "514"
      port: 514
      protocol: UDP
      targetPort: 5514
    - name: "601"
      port: 601
      targetPort: 6601
    - name: "6514"
      port: 6514
      targetPort: 6514
  selector:
    io.kompose.service: syslog-ng
  type: LoadBalancer
status:
  loadBalancer: {}
