apiVersion: v1
kind: Service
metadata:
  labels:
    app: syslog-ng
  name: syslog-ng
spec:
  ports:
    - name: "514"
      port: 514
      protocol: UDP
      targetPort: 5514
    - name: "601"
      port: 601
      targetPort: 6601
    - name: "6514"
      port: 6514
      targetPort: 6514
  selector:
    app: syslog-ng
  loadBalancerIP: 192.168.10.205
  type: LoadBalancer
