apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-csi"
  name: syslog-ng-cfg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
