apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: syslog-ng
  name: syslog-ng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog-ng
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: syslog-ng
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Europe/Athens
          image: lscr.io/linuxserver/syslog-ng:latest
          name: syslog-ng
          ports:
            - containerPort: 5514
              protocol: UDP
            - containerPort: 6601
            - containerPort: 6514
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - mountPath: /config
              name: syslog-ng-cfg
            - mountPath: /var/log
              name: syslog-ng-logs
      restartPolicy: Always
      volumes:
        - name: syslog-ng-cfg
          persistentVolumeClaim:
            claimName: syslog-ng-cfg
        - name: syslog-ng-logs
          persistentVolumeClaim:
            claimName: syslog-ng-logs
