apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
  name: syslog-ng-logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
